CREATE TYPE project_status AS ENUM ('ACTIVO', 'PAUSADO', 'FINALIZADO', 'CANCELADO');

CREATE TYPE task_status AS ENUM ('PENDIENTE', 'EN_PROGRESO', 'COMPLETADA');

CREATE TYPE task_priority AS ENUM ('BAJA', 'MEDIA', 'ALTA', 'URGENTE');

CREATE TYPE notification_channel AS ENUM ('WHATSAPP', 'EMAIL', 'AMBOS');
